### ISSUE TITLE
Issues exporting network to graphml

### ISSUE THREAD

**Issue by eyseman** [jboynyc/textnets#28]
* Textnets version: 0.4.11
* Python version: 3.8.5
* Operating System: Windows 10 20H2 (WSL2 - Ubuntu 20.04 LTS) 

### Description

The idea is to export the generated network in graphml or a similar structure to further analyse and visualize it in tools such as Gephi or Cytoscape. I tried to use the command line tool (I saw the notice concerning it being depricated). "Text.txt" is a file with a .csv structure. I also tried a file with pure text, still did not work.

Is there a way to export the network besides the described, old way via CLI?

Thanks!
Cheers, eyseman

### What I Did

```
textnets text.txt --lex noun_phrases --node-type term --format graphml --output network.txt
Traceback (most recent call last):
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/bin/textnets", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/lib/python3.8/site-packages/textnets/cli.py", line 51, in main
    c = Corpus.from_files(corpus)
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/lib/python3.8/site-packages/textnets/corpus.py", line 158, in from_files
    return cls(df, doc_col="raw", lang=lang)
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/lib/python3.8/site-packages/textnets/corpus.py", line 63, in __init__
    if documents.isna().any():
  File "/mnt/c/Users/TLampoltshammer/code/text-nets/lib/python3.8/site-packages/pandas/core/generic.py", line 1329, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by jboynyc** [comment]
There's a few things going on here, aside from the command-line interface being deprecated.

1. The argument has to be a folder containing a collection of texts, not a single text file.
2. The output goes to stdout, so you should use a shell redirect (`>`) to write the output to a file; there is no `--output` option.
3. The error message is incredibly unhelpful 🤦

Here's how you can create a graphml file without using the command-line tool:

```python
corpus = Corpus.from_csv("text.txt", label_col="group", doc_col="text")
np = corpus.noun_phrases()
terms = Textnet(np).project(node_type="term")
terms.graph.write("network.graphml")
```

`terms.graph` is an instance of igraph's `Graph` class, which is documented [here](https://igraph.org/python/doc/igraph.Graph-class.html#write).

**Comment by jboynyc** [comment]
I'm closing this issue for now; feel free to reopen it if things don't work out for you, or file a new one requesting improved documentation.
